### PR TITLE
Notebook/multilevel hierarchy

### LINKED ISSUE #1336: Notebook example for a nested hierarchical model
I'm interested in contributing a notebook example showing how to setup a nested hierarchical model.  I'm opening a ticket based on the suggestion from issue #189 to see if this is a valuable contribution.  

The notebook would outline a model similar to https://forum.pyro.ai/t/add-additional-level-in-hierarchical-model/3022/5 and https://forum.pyro.ai/t/hierarchical-model-with-two-levels/3775/6.  I plan to copy or extend the [Bayesian Hierarchical Linear Regression notebook](https://github.com/pyro-ppl/numpyro/blob/332dfd2dd0aa4a264da6d4ea190e0fed6a2ddf3b/notebooks/source/bayesian_hierarchical_linear_regression.ipynb) and include "SmokingStatus" as a partially pooled variable.

### PR DESCRIPTION
**Pull request by cstoafer**
These updates expand upon an existing notebook to illustrate how to add an intermediate level to hierarchical models.  

Closes #1336

### CODE REVIEW

**Comment by cstoafer** [comment]
I followed the contributing guidelines and ran into a few issues:

- I needed to install additional dependencies by installing with `pip install -e .[dev,test,doc,examples]` to avoid import errors.  Should I update the contributing guidelines?
- I needed to install pandoc separately.
- There were still some failing tests when I ran `make test` in my environment:
    ```
    =================================================== short test summary info ===================================================
    FAILED test/infer/test_mcmc.py::test_chain[parallel-False] - UserWarning: There are not enough devices to run parallel chain...
    FAILED test/infer/test_mcmc.py::test_chain[parallel-True] - UserWarning: There are not enough devices to run parallel chains...
    FAILED test/infer/test_mcmc.py::test_chain[sequential-False] - UserWarning: There are not enough devices to run parallel cha...
    FAILED test/infer/test_mcmc.py::test_chain[sequential-True] - UserWarning: There are not enough devices to run parallel chai...
    FAILED test/infer/test_mcmc.py::test_chain[vectorized-False] - UserWarning: There are not enough devices to run parallel cha...
    FAILED test/infer/test_mcmc.py::test_chain[vectorized-True] - UserWarning: There are not enough devices to run parallel chai...
    FAILED test/infer/test_mcmc.py::test_chain_jit_args_smoke[False-parallel] - UserWarning: There are not enough devices to run...
    FAILED test/infer/test_mcmc.py::test_chain_jit_args_smoke[True-parallel] - UserWarning: There are not enough devices to run ...
    ======================= 8 failed, 5533 passed, 831 skipped, 25 xfailed, 1 warning in 4319.76s (1:11:59) =======================
    Makefile:23: recipe for target 'test' failed
    make: *** [test] Error 1
    ```

- `make doctest` failed and I'm not sure how to resolve the issue:

    ```
    JAX_PLATFORM_NAME=cpu make -C docs doctest
    make[1]: Entering directory '/home/cstoafer/indeed/numpyro/docs'
    Running Sphinx v4.4.0
    loading intersphinx inventory from https://docs.python.org/3/objects.inv...
    loading intersphinx inventory from http://docs.scipy.org/doc/numpy/objects.inv...
    loading intersphinx inventory from https://jax.readthedocs.io/en/latest/objects.inv...
    loading intersphinx inventory from http://docs.pyro.ai/en/stable/objects.inv...
    intersphinx inventory has moved: http://docs.scipy.org/doc/numpy/objects.inv -> https://numpy.org/doc/stable/objects.inv
    intersphinx inventory has moved: http://docs.pyro.ai/en/stable/objects.inv -> https://docs.pyro.ai/en/stable/objects.inv
    generating gallery...
    Using Sphinx-Gallery to convert rst text blocks to markdown for .ipynb files.
    generating gallery for examples... [100%] hsgp.py
    computation time summary:
    building [mo]: targets for 0 po files that are out of date
    building [doctest]: targets for 56 source files that are out of date
    updating environment: [new config] 56 added, 0 changed, 0 removed
    reading sources... [100%] utilities

    Warning, treated as error:
    /home/cstoafer/indeed/numpyro/docs/source/tutorials/discrete_imputation.ipynb:15:Content block expected for the "raw" directive; none found.
    Makefile:20: recipe for target 'doctest' failed
    make[1]: *** [doctest] Error 2
    make[1]: Leaving directory '/home/cstoafer/indeed/numpyro/docs'
    Makefile:20: recipe for target 'doctest' failed
    make: *** [doctest] Error 2
    ```

**Comment by fehiepsi** [comment]
> Should I update the contributing guidelines?

Please do, thank you!

> some failing tests

Those tests require an [XLA_FLAGS](https://github.com/pyro-ppl/numpyro/blob/master/.github/workflows/ci.yml#L110) to run parallel chains. Please just ignore the warning. If you are interested in resolving the issue, [here](https://github.com/pyro-ppl/numpyro/blob/master/test/infer/test_mcmc.py#L531) is where we skip pytest. It is not robust (in case users have their own XLA_FLAGS). I think we need to move `skipif` inside the test and check for the number of devices with [jax.local_device_count](https://jax.readthedocs.io/en/latest/_autosummary/jax.local_device_count.html#jax.local_device_count).

**Comment by cstoafer** [comment]
Thank you @fehiepsi, I've updated the notebook based on your comments and updated the installation instructions for contributing.

**Review by fehiepsi — APPROVED** [review]

**Comment by fehiepsi** [comment]
Thanks, @cstoafer!

**Pull request merged**
