### PR TITLE
make sure to use new sample_fn for new data

### LINKED ISSUE #441: Avoid recompilation in MCMC.run with new data
This can be important for saving on compilation cost. 

There seems to be some bug in in HMC/NUTS kernels or the MCMC class due to which this doesn't work currently. See. @null-a's [snippet](https://gist.github.com/null-a/fa9e2038630daf104a7ed3821799db57) for details.

### PR DESCRIPTION
**Pull request by fehiepsi**
Addresses the bug in #441.

### CODE REVIEW

**Comment by neerajprad** [comment]
IIUC..this will still cause the sample function to be recompiled, which takes any benefits from reusing `.run`. Correct me if I'm mistaken? We should definitely merge this as a bug fix, but fixing #441 will require us to solve this without having to recompile in `collect_fn`.

**Comment by fehiepsi** [comment]
Yes, it will recompile. I think it is better to let users decide when they want to recompile, rather than handling it automatically.

**Comment by fehiepsi** [comment]
I think we can use @null-a test. :D

**Comment by neerajprad** [comment]
@fehiepsi - Feel free to merge this at your convenience.

**Pull request merged**
