### PR TITLE
Add inference guide to readme

### PR DESCRIPTION
**Pull request by martinjankowiak**
We have a lot more inference algorithms then we once did so it's useful to offer some kind of guide in the README

### CODE REVIEW

**Review by fehiepsi — APPROVED** [review]
This overview is super helpful!! Thanks, Martin!

**Comment by martinjankowiak** [comment]
@fehiepsi we should double check which mcmc algorithms automatically do enumeration and which do not so that that information can be incorporated into the overview

**Comment by fehiepsi** [comment]
I think all mcmc algorithms currently do enumeration automatically (including nested sampler). For DiscreteHMCGibbs, we will do enumeration (if possible) over discrete sites that are marked "enumerated".

**Comment by martinjankowiak** [comment]
what about e.g. HCMCECS? i guess there you'd need to compute a proxy for the enumerated potential which probably isn't supported without additional work?

**Comment by fehiepsi** [comment]
You are right. It is fine for the default value `proxy=None`. We need to raise an error for taylor proxy.

**Pull request merged**
