### PR TITLE
Make possible to fix the number of LF steps and tune the step size

### LINKED ISSUE #1678: Zero HMC acceptance rate for standard normal
Step size tuning in HMC fails on a standard Gaussian. Acceptance rate is 0, regardless of the step size. The problem goes away with NUTS. 
The problem is shown in this notebook: 
https://colab.research.google.com/drive/1QBrROnhUEAOcP3Q9-pT8AfwFjZdu9y1y?usp=sharing

### PR DESCRIPTION
**Pull request by yayami3**
Closes #1678

### CODE REVIEW

**Comment by fehiepsi** [comment]
I guess the latest working version is `jaxns=2.2.6`. Could you limit the version [here](https://github.com/pyro-ppl/numpyro/blob/master/setup.py#L66) and [here](https://github.com/pyro-ppl/numpyro/blob/master/docs/requirements.txt#L7)

**Comment by fehiepsi** [comment]
Thanks, @yayami3! Could you add a simple test for this?

**Comment by yayami3** [comment]
test added. 

@fehiepsi 
pls review!

**Review by fehiepsi — APPROVED** [review]
The changes look great!! thanks @yayami3!

**Pull request merged**
