### PR TITLE
Only use `figure_format = svg` in website

### PR DESCRIPTION
**Pull request by fehiepsi**
Addresses #445.

@neerajprad It seems that logistic regression example does not work with the caching pattern. In particular, kernel.init is called with new kwargs, so we need to reconstruct `kernel._init_fn` and `kernel._sample_fn`.

### CODE REVIEW

**Comment by neerajprad** [comment]
> @neerajprad It seems that logistic regression example does not work with the caching pattern. In particular, kernel.init is called with new kwargs, so we need to reconstruct kernel._init_fn and kernel._sample_fn.

Does it throw an exception? Could you share some code snippet and elaborate on what it is doing counter to expectations?

**Comment by fehiepsi** [comment]
@neerajprad For now, you can see the error with exception [here](https://nbviewer.jupyter.org/github/pyro-ppl/numpyro/blob/6537a0f81625a37e046d8bb8af934e2d4b77556d/notebooks/source/bayesian_regression.ipynb#Model-2:-Predictor---Median-Age-of-Marriage). I'll provide a simple replicate example later. :)

**Comment by neerajprad** [comment]
Oh..I was looking at the logistic regression example, not that one. Don't worry about replicating it; I'll run it and push a fix for that.

**Comment by fehiepsi** [comment]
Oppss, sorry. I meant bayesian regression. @@

**Comment by neerajprad** [comment]
@fehiepsi - is this good to merge?

**Comment by fehiepsi** [comment]
Oh no, I haven't run this again. >"<

**Comment by fehiepsi** [comment]
@neerajprad I think it is good to merge when tests pass. :) I only add the check for the flag "NUMPYRO_SPHINXBUILD" in the environment to disable/enable "svg" format and rerun those notebooks.

**Pull request merged**
