### PR TITLE
Fix transformed distribution validate samples

### PR DESCRIPTION
**Pull request by xidulu**
Fix https://github.com/pyro-ppl/numpyro/issues/1463

### CODE REVIEW

**Review by fehiepsi — APPROVED** [review]

**Comment by xidulu** [comment]
@fehiepsi 
Any idea about why the CI failed? 🤔
It looks kind of annoying to me...

Thanks

**Comment by martinjankowiak** [comment]
@xidulu you probably want to merge in master after #1464

**Comment by xidulu** [comment]
@martinjankowiak @fehiepsi 
It seems that #1464 has been merged. Could you help retrigger the CI and see if my PR can get merged?
Thanks

**Comment by fehiepsi** [comment]
@xidulu You will need to merge the master branch to your branch. Otherwise, CI will fail for the same reason.

**Comment by fehiepsi** [comment]
Thanks @xidulu

**Pull request merged**
