### PR TITLE
add discrete imputation example

### PR DESCRIPTION
**Pull request by vanAmsterdam**
As discussed in #726 

In addition to showcasing this method for automatically enumerating missing covariates, it discusses several forms of missing data and how to handle them.

Currently it depends on the graphviz package to generate diagrams

### CODE REVIEW

**Comment by martinjankowiak** [comment]
this is great!

a few nits/suggestions:
- "Inference by automatic is implemented in numpyro and allows for a very conveniant way of dealing with missing discrete data." =>
"Inference with automatic enumeration of discrete variables is implemented in numpyro and allows for a very conveni**e**nt way of dealing with missing discrete data."
- typo "condiditional"
- define "MAR"
- add a bit more explanation of your models (not just graphical structure)?
- typos "interes", "Obsiously"

**Review by fehiepsi — COMMENTED** [review]
Awesome tutorial! The content is great. It is a good idea to use `-1` for missing discrete data. Thanks, @vanAmsterdam! I just have two small comments:
+ could you rename the file to `discrete_imputation.ipynb` (and modifying the file name in `index.rst` too)
+ you can remove
```
    A_obsidx = jnp.where(A_isobs)[0]
    A_missidx = jnp.where(1 - A_isobs)[0]
```
in all models

**Comment by vanAmsterdam** [comment]
thanks for both your suggestions; I've added some concrete examples of what the variables could represent. How do you like them? Do you have other suggestions?

**Review by fehiepsi — APPROVED** [review]
LGTM pending further comments by @martinjankowiak! Thanks for your contribution, @vanAmsterdam !

**Review by martinjankowiak — APPROVED** [review]
lgtm but there are still a few typos:
"conveniant"
"condiditional"

**Review by fehiepsi — APPROVED** [review]
💯

**Pull request merged**
