### PR TITLE
explicit num_warmup, num_samples arguments for MCMC

### LINKED ISSUE #1038: order of args to mcmc is inconsistent between pyro and numpyro
I see that [pyro.mcmc](https://num.pyro.ai/en/stable/mcmc.html) uses (kernel, num_samples, warmup_steps)
but [numpyro.mcmc](https://num.pyro.ai/en/stable/mcmc.html) uses (kernel, warmup_steps, num_samples), which is a bit confusing.

### PR DESCRIPTION
**Pull request by fehiepsi**
Resolves #1038.

This might break things but in the long run, I think this requirement is good. Using only the numbers `MCMC(kernel, 500, 500)` is a bit confusing and should be discouraged.

### CODE REVIEW

**Review by fritzo — APPROVED** [review]
LGTM, indeed this seems like the most conservative resolution to #1038.

**Comment by fehiepsi** [comment]
Thanks for reviewing! :)

**Comment by alexander-maier** [comment]
Is this right? Calling
```python
compat.infer.MCMC(kernel, num_warmup=100, num_samples=1000)
```
throws an error since no kwargs are handed to `mcmc.MCMC`. Also, shouldnt the correct `compat` call be
```python
compat.infer.MCMC(kernel, warmup_steps=100, num_samples=1000)?
```
Thanks

**Comment by fehiepsi** [comment]
Oh, we haven't updated the compat module for this change. It should have the later signatures. Could you make a separate issue for this @alexander-maier ?

**Comment by alexander-maier** [comment]
#1321

**Pull request merged**
