### PR TITLE
Downgrade numpy version in setup and docs build

### PR DESCRIPTION
**Pull request by neerajprad**
See - https://github.com/google/jax/issues/1912

### CODE REVIEW

**Comment by neerajprad** [comment]
I'm still noticing issues with the build; will update once those are fixed.

**Comment by fehiepsi** [comment]
I think you would need to ping jax/jaxlib versions. Currently, #496 is blocked.

**Comment by neerajprad** [comment]
Thanks @fehiepsi, that was the issue. I think this should now pass.

**Comment by neerajprad** [comment]
Ready to merge when build is green.

**Pull request merged**
