### PR TITLE
Computing number of gradient evaluations example

### PR DESCRIPTION
**Pull request by andyElking**
Hi,

I made a small addition to the end of the example about Bayesian logistic regression. I hope this is what you had in mind when you asked me to make a contribution in #1838.

Best,
Andy

### CODE REVIEW

**Comment by fehiepsi** [comment]
Could you run `make format` to fix the lint issue?

**Comment by andyElking** [comment]
Sorry about that, I fixed the linting now.

**Review by fehiepsi — APPROVED** [review]
The change looks great! Thanks, @andyElking !

**Comment by andyElking** [comment]
Great news, thanks so much!

**Pull request merged**
