### PR TITLE
mask log prob of univariate distribution

### PR DESCRIPTION
**Pull request by fehiepsi**
Addresses #373.

At first, I thought that we need a general approach to this issue. However, when plotting out the log_prob of all distributions, we can see that there are just a few distributions that have this issue. So I go ahead and do the masking job for each of them, instead of trying to think of a general solution.

Affected distributions:
+ Exponential
+ HalfNormal/HalfCauchy/TruncatedNormal/TruncatedCauchy
+ Uniform
+ Bernoulli
+ Categorical

Not tested distributions:
+ all multivariate ones

### CODE REVIEW

**Comment by neerajprad** [comment]
Refer to my comment in #373. I think we shouldn't turn this on by default. We call distribution methods many many times and for large models, this will have non-negligible overhead. How about we instead turn on distributions validation check by default, and provide a class attribute to turn it off like in PyTorch. That should be sufficient for the use cases you mention.

**Comment by fehiepsi** [comment]
Though I don't think we should care about masking op, this solution might not be good.

> turn on distributions validation check by default

I think that we can have the check by default (though it will be slower for support-checking and we need a workaround to disable the check inside jit/vmap/pmap). A context manager `numpyro.enable_validation()` would be helpful (somehow we forgot about it during refactorings?). Let's assume that we keep the default behavior (faster, no masking) and discuss what we should do if we turn on `checking`. I don't think that raising an error for out-of-support value is a good solution because those values should have probability `0`. A better solution to me is to raise a warning and return a masked result.

```
log_prob = ...
if self._validate_args:
    mask = self._validate_sample(value)
    log_prob = np.where(mask, log_prob, -np.inf)
```
and `self._validate_sample` is implemented as
```
mask = support(value)
if check is outside of jit/vmap/pmap:
    if np.all(mask):  # together with 
        warning("value is outside of support"
    return mask
```
WDYT? This is a more reasonable approach to me.

**Comment by neerajprad** [comment]
> A better solution to me is to raise a warning and return a masked result.

That sounds reasonable to me. Our current design forces the user to do this masking instead, but I like your idea of doing this masking and returning `-inf` for out of support values, if we can do this consistently for all distributions.

**Comment by fehiepsi** [comment]
Yeah, let me create another PR for this.

**Pull request closed without merging**
