### PR TITLE
Bump to version 0.2

### PR DESCRIPTION
**Pull request by neerajprad**

### CODE REVIEW

**Comment by fehiepsi** [comment]
@neerajprad Will we need to update README file? Do we need to address #184 (PyPI rendering) and #281 (check version in examples/tutorials) too?

**Comment by neerajprad** [comment]
> Do we need to address #184 (PyPI rendering) 

We shouldn't need any changes for this. We just need to use `twine` instead of `setup sdist`, I'll check again.

> and #281 (check version in examples/tutorials, sorry I just recall this - I did close that issue without noticing this task) too?

I think given all the breaking changes in JAX, this might be a good thing to do. I'll add it to the examples in this PR.

**Comment by fehiepsi** [comment]
@neerajprad While editing release note, I found that MVN/PRNGIdentity is not exposed to the docs, could you pls add them in this PR too?

**Comment by fehiepsi** [comment]
@neerajprad I have taken my pass at the release note. :)

**Pull request merged**
