### PR TITLE
Fix enum plate not save global dims

### PR DESCRIPTION
**Pull request by fehiepsi**
Fixes a bug detected by @xidulu in #769.

### CODE REVIEW

**Review by fritzo — COMMENTED** [review]
Should you also unconditionally call `super()...` in `.process_message()`? It seems like the logic in `.process_message()` and `.postprocess_message()` should agree. @eb8680 ?

**Comment by eb8680** [comment]
@fehiepsi I'm not sure this is a bug, can you give an example of the actual and expected behavior before and after this change?

**Comment by fehiepsi** [comment]
> can you give an example of the actual and expected behavior

I am not sure. I observed that
```
def model(X, y):
    N, d = X.shape
    with numpyro.plate('d', d, dim=-1):
        pi = numpyro.sample('pi', dist.Beta(0.5, 0.5))
        xi = numpyro.sample('xi', dist.Bernoulli(probs=pi))
        w = numpyro.sample('w', dist.Normal(0., 10.0))
    loc = np.matmul(X, (w * xi)[..., None]).squeeze(-1)
    with numpyro.plate('N', N, dim=-1):
        return numpyro.sample('obs', dist.Normal(loc), obs=y)
```
will generate a variable `obs` with dimensions `xi` and `d`. With the change in this PR, the variable `obs` will get dimensions `xi` and `N`. But probably it is your intention. If so, I will close this PR.

**Comment by eb8680** [comment]
> But probably it is your intention

It's not obvious to me what the correct behavior is here - this fix would make your example behave (arguably) correctly, but would also break enumeration and plate dimension semantics in non-intuitive ways in models that for whatever reason use many plates.  For now I think a better solution is to point users to Pyro's enumeration tutorial to explain what's tractable and what's not and help them rewrite models with cross-plate dependencies to have tree-structured plate nesting, e.g. by replacing some plates with `.to_event` calls.

**Comment by fehiepsi** [comment]
Yeah, I agree there should be some validation code or better error messages.

So I rewrite the model into
```python
def model(X, y):
    N, d = X.shape
    with numpyro.plate('d', d, dim=-1):
        pi = numpyro.sample('pi', dist.Beta(0.5, 0.5))
        w = numpyro.sample('w', dist.Normal(0., 10.0))

    ws = []
    for k in range(d):
        xi_k = numpyro.sample(f'xi_{k}', dist.Bernoulli(probs=pi[k]))
        w_k = np.where(xi_k, w[k], 0)
        ws.append(w_k)
    ws = np.stack(np.broadcast_arrays(*ws), axis=-1)

    loc = np.matmul(X, ws[..., None]).squeeze(-1)
    with numpyro.plate('N', N, dim=-1):
        return numpyro.sample('obs', dist.Normal(loc), obs=y)
```

<details> <summary>Full code</summary>

```python
import jax
from jax import random
import jax.numpy as np
import numpyro
import numpyro.distributions as dist
from numpyro.contrib.indexing import Vindex
from numpyro.infer import NUTS, MCMC
jax.config.disable_omnistaging()

def generate_data(key, n_samples=100, n_features=100, features_kept=10):
    X = random.normal(key, (n_samples, n_features))
    # Create weights with a precision lambda_ of 4.
    lambda_ = 4.
    w = np.zeros(n_features)
    # Only keep 10 weights of interest
    relevant_features = random.choice(
        key, np.arange(n_features), (features_kept,), False)
    w = jax.ops.index_update(
        w,
        relevant_features,
        dist.Normal(loc=0, scale=1. / np.sqrt(lambda_)).sample(key, (features_kept,))
    )
    # Create noise with a precision alpha of 50.
    alpha_ = 50.
    noise = dist.Normal(loc=0, scale=1. / np.sqrt(alpha_)).sample(key, (n_samples,))
    # Create the target
    y = np.dot(X, w) + noise
    return X, y, w

X, y, w = generate_data(random.PRNGKey(0), 4, 3, 2)
X.shape, y.shape

mcmc = MCMC(NUTS(model), 500, 500)
mcmc.run(random.PRNGKey(0), X, y)
```
</details>

The factors will be
```
[Tensor(Traced<ConcreteArray([-1.401806  -2.1019688 -1.7583057])>with<JVPTrace(level=1/0)>
  with primal = DeviceArray([-1.401806 , -2.1019688, -1.7583057], dtype=float32)
       tangent = Traced<ShapedArray(float32[3]):JaxprTrace(level=0/0)>, OrderedDict([('d', Bint[3, ])]), 'real'), Tensor(Traced<ConcreteArray([-0.44382608 -0.09374487 -0.2655763 ])>with<JVPTrace(level=1/0)>
  with primal = DeviceArray([-0.44382608, -0.09374487, -0.2655763 ], dtype=float32)
       tangent = Traced<ShapedArray(float32[3]):JaxprTrace(level=0/0)>, OrderedDict([('d', Bint[3, ])]), 'real'), Tensor(Traced<ConcreteArray([-3.229965  -3.2219462 -3.239487 ])>with<JVPTrace(level=1/0)>
  with primal = DeviceArray([-3.229965 , -3.2219462, -3.239487 ], dtype=float32)
       tangent = Traced<ShapedArray(float32[3]):JaxprTrace(level=0/0)>, OrderedDict([('d', Bint[3, ])]), 'real'), Tensor(Traced<ConcreteArray([-0.82561004 -0.576196  ])>with<JVPTrace(level=1/0)>
  with primal = DeviceArray([-0.82561004, -0.576196  ], dtype=float32)
       tangent = Traced<ShapedArray(float32[2]):JaxprTrace(level=0/0)>, OrderedDict([('xi_0', Bint[2, ])]), 'real'), Tensor(Traced<ConcreteArray([-1.9481988  -0.15376975])>with<JVPTrace(level=1/0)>
  with primal = DeviceArray([-1.9481988 , -0.15376975], dtype=float32)
       tangent = Traced<ShapedArray(float32[2]):JaxprTrace(level=0/0)>, OrderedDict([('xi_1', Bint[2, ])]), 'real'), Tensor(Traced<ConcreteArray([-0.25015315 -1.5081525 ])>with<JVPTrace(level=1/0)>
  with primal = DeviceArray([-0.25015315, -1.5081525 ], dtype=float32)
       tangent = Traced<ShapedArray(float32[2]):JaxprTrace(level=0/0)>, OrderedDict([('xi_2', Bint[2, ])]), 'real'), Tensor(Traced<ConcreteArray([[[[-1.3046664  -0.977973   -1.213804   -0.9663509 ]
   [-1.1421189  -1.0131184  -0.93338925 -2.189458  ]]

  [[-1.6366069  -1.0236161  -1.8565254  -1.0466189 ]
   [-0.9796202  -0.9701585  -1.2164943  -2.5236025 ]]]


 [[[-0.91963637 -1.3886205  -1.6084142  -0.9411368 ]
   [-2.0575821  -2.4446356  -1.0850296  -1.4972053 ]]

  [[-0.982695   -1.2846785  -2.4955258  -0.9190271 ]
   [-1.6262016  -2.25209    -1.6125246  -1.7289721 ]]]])>with<JVPTrace(level=1/0)>
  with primal = DeviceArray([[[[-1.3046664 , -0.977973  , -1.213804  , -0.9663509 ],
                               [-1.1421189 , -1.0131184 , -0.93338925, -2.189458  ]],
                
                              [[-1.6366069 , -1.0236161 , -1.8565254 , -1.0466189 ],
                               [-0.9796202 , -0.9701585 , -1.2164943 , -2.5236025 ]]],
                
                
                             [[[-0.91963637, -1.3886205 , -1.6084142 , -0.9411368 ],
                               [-2.0575821 , -2.4446356 , -1.0850296 , -1.4972053 ]],
                
                              [[-0.982695  , -1.2846785 , -2.4955258 , -0.9190271 ],
                               [-1.6262016 , -2.25209   , -1.6125246 , -1.7289721 ]]]],            dtype=float32)
       tangent = Traced<ShapedArray(float32[2,2,2,4]):JaxprTrace(level=0/0)>, OrderedDict([('_pyro_dim_5', Bint[2, ]), ('xi_2', Bint[2, ]), ('xi_1', Bint[2, ]), ('d', Bint[4, ])]), 'real')]
```

We can see that the factor `obs` has wrong dimensions `_pyro_dim_5`, `xi_2`, `xi_1`, `d`. I would expect the correct dimensions are `xi_2`, `xi_1`, `xi_0`, and `N`. The commit in this PR only fixes `d` -> `N`. The remaining dimensions are still incorrect. Do you have an idea way? Or this pattern is also not supported?

**Comment by fehiepsi** [comment]
> would also break enumeration and plate dimension semantics in non-intuitive ways in models that for whatever reason use many plates

It seems that I don't understand the current semantics. If the change breaks things, let me create a separate issue for the above non-working example and learn more about Pyro enumeration to fix it.

**Pull request closed without merging**
