### PR TITLE
build: refactor build infrastructure

### PR DESCRIPTION
**Pull request by nstarman**
This PR refactors the build infrastructure to
1. remove the setup.py in favor of pyproject.toml
2. dynamically generate the version from the pyproject (this is not a VCS dynamic versioning)
3. be compatible with `uv` but still all other tools, like `conda`, 
4. use `src` folder layout.

### CODE REVIEW

**Comment by fehiepsi** [comment]
Hi @nstarman, thanks for the refactor. We would prefer to keep the current setup. I'm not sure why we need to be compatible with uv (shouldn't uv thing be compatible with the python ecosystem?) and why we need to use the src layout.

**Comment by nstarman** [comment]
`uv` is compatible with the python ecosystem. It just adds config to `pyproject.toml` for development and adds a lockfile, which is useful.
Is there a reason for keeping the outdated `setup.py`?
When I've been doing dev in my last PR my editable build is producing a `numpyro.egg-info` in the top-level env. The `src` layout is better for isolating dev environments. Because of `git-mv` current PRs can rebase without consequence.

**Comment by fehiepsi** [comment]
re setup.py: https://packaging.python.org/en/latest/discussions/setup-py-deprecated/#setup-py-deprecated

**Comment by nstarman** [comment]
> re setup.py: https://packaging.python.org/en/latest/discussions/setup-py-deprecated/#setup-py-deprecated

Yes, it's not deprecated. I was careful to use "outdated" as new standards have superseded `setup.py`, offering standardization, better integrations with developer tooling, safety from arbitrary code execution, improved reproducibility in builds, support for PEP 517/518, and longevity (version 21.3 of pip has started moving away from supporting editable installs via setup.py)

**Comment by fehiepsi** [comment]
Thanks. Could you make a new PR just for setup.py changes?

**Comment by fehiepsi** [comment]
Close, in favor of https://github.com/pyro-ppl/numpyro/pull/1891

**Pull request closed without merging**
