### PR TITLE
improve turning condition

### PR DESCRIPTION
**Pull request by fehiepsi**
This PR tries to address #393.

### Context

To check the turning condition, we need to compute `dot(v_left, z_right - z_left)` and `dot(v_right, z_right - z_left)`. Then we approximate `z_right - z_left` by `r_sum - r_left` or `r_sum - r_right`. As pointed out by the user **nhuurre** at [this thread](https://discourse.mc-stan.org/t/nuts-misses-u-turns-runs-in-circles-until-max-treedepth/9727/58), it is better to approximate `z_right - z_left` by
`r_sum - (r_left + r_right) / 2`.

### Test
On the model #393 

```
from jax import numpy as np, random
import numpyro as npyro; npyro.set_host_device_count(4)
import numpyro.distributions as dist
from numpyro.infer import NUTS, MCMC

def model():
    b = npyro.sample('b', dist.Normal(0, 1))
    sigma = npyro.sample('sigma', dist.Uniform(0, 1))
    npyro.sample('y', dist.Normal(b, sigma), obs=np.array([0, 0.1, 1]))

for i in range(5):
    mcmc = MCMC(NUTS(model), 1000, 1000, num_chains=4, chain_method='vectorized')
    mcmc.run(random.PRNGKey(i))
    mcmc.print_summary()
```
gives us
```
sample: 100%|██████████| 2000/2000 [00:07<00:00, 266.53it/s]



                mean       std    median      5.0%     95.0%     n_eff     r_hat
         b      0.31      0.34      0.31     -0.29      0.84   8105.90      0.99
     sigma      0.63      0.19      0.62      0.35      0.95   8135.58      0.99


sample: 100%|██████████| 2000/2000 [00:07<00:00, 274.86it/s]



                mean       std    median      5.0%     95.0%     n_eff     r_hat
         b      0.32      0.35      0.33     -0.29      0.84   8780.48      1.00
     sigma      0.63      0.19      0.62      0.33      0.95   7681.27      1.01


sample: 100%|██████████| 2000/2000 [00:07<00:00, 273.77it/s]



                mean       std    median      5.0%     95.0%     n_eff     r_hat
         b      0.32      0.35      0.32     -0.26      0.89   8724.73      0.99
     sigma      0.63      0.19      0.61      0.34      0.95   7996.22      1.00


sample: 100%|██████████| 2000/2000 [00:07<00:00, 270.22it/s]



                mean       std    median      5.0%     95.0%     n_eff     r_hat
         b      0.32      0.35      0.33     -0.28      0.87   7574.28      1.01
     sigma      0.63      0.19      0.63      0.34      0.95   7719.02      1.01


sample: 100%|██████████| 2000/2000 [00:07<00:00, 270.19it/s]



                mean       std    median      5.0%     95.0%     n_eff     r_hat
         b      0.32      0.36      0.32     -0.32      0.87   7915.71      0.99
     sigma      0.63      0.19      0.63      0.37      0.98   7461.49      1.02


```

### CODE REVIEW

**Comment by fehiepsi** [comment]
### test on HMM example, num_warmup=5000, num_samples=5000

```


                          mean       std    median      5.0%     95.0%     n_eff     r_hat
  emission_prob[0,0]      0.00      0.01      0.00      0.00      0.01   8550.95      1.00
  emission_prob[0,1]      0.00      0.01      0.00      0.00      0.01   8428.96      1.00
  emission_prob[0,2]      0.17      0.04      0.17      0.10      0.24   4955.55      1.00
  emission_prob[0,3]      0.79      0.05      0.80      0.71      0.88   5264.78      1.00
  emission_prob[0,4]      0.00      0.01      0.00      0.00      0.01   4525.66      1.00
  emission_prob[0,5]      0.01      0.02      0.00      0.00      0.02   6042.85      1.00
  emission_prob[0,6]      0.01      0.02      0.00      0.00      0.02   4302.26      1.00
  emission_prob[0,7]      0.00      0.00      0.00      0.00      0.00   7023.45      1.00
  emission_prob[0,8]      0.01      0.02      0.00      0.00      0.02   4678.46      1.00
  emission_prob[0,9]      0.00      0.00      0.00      0.00      0.00   6965.07      1.00
  emission_prob[1,0]      0.00      0.01      0.00      0.00      0.01   5727.43      1.00
  emission_prob[1,1]      0.00      0.01      0.00      0.00      0.01   5834.89      1.00
  emission_prob[1,2]      0.00      0.01      0.00      0.00      0.00   5173.98      1.00
  emission_prob[1,3]      0.00      0.01      0.00      0.00      0.01   6697.10      1.00
  emission_prob[1,4]      0.00      0.01      0.00      0.00      0.01   4404.79      1.00
  emission_prob[1,5]      0.00      0.01      0.00      0.00      0.01   7058.46      1.00
  emission_prob[1,6]      0.68      0.04      0.69      0.62      0.75   4822.65      1.00
  emission_prob[1,7]      0.00      0.00      0.00      0.00      0.00   7432.42      1.00
  emission_prob[1,8]      0.30      0.04      0.30      0.24      0.36   4934.25      1.00
  emission_prob[1,9]      0.00      0.00      0.00      0.00      0.00   8001.20      1.00
  emission_prob[2,0]      0.17      0.02      0.17      0.14      0.21   5014.69      1.00
  emission_prob[2,1]      0.03      0.01      0.03      0.02      0.05   4703.30      1.00
  emission_prob[2,2]      0.00      0.00      0.00      0.00      0.00   6156.92      1.00
  emission_prob[2,3]      0.03      0.02      0.02      0.00      0.05   4239.32      1.00
  emission_prob[2,4]      0.00      0.00      0.00      0.00      0.00   4988.74      1.00
  emission_prob[2,5]      0.76      0.03      0.76      0.72      0.80   4975.17      1.00
  emission_prob[2,6]      0.00      0.01      0.00      0.00      0.00   4831.57      1.00
  emission_prob[2,7]      0.00      0.00      0.00      0.00      0.00   6896.66      1.00
  emission_prob[2,8]      0.00      0.01      0.00      0.00      0.01   4425.56      1.00
  emission_prob[2,9]      0.00      0.00      0.00      0.00      0.00   6914.62      1.00
transition_prob[0,0]      0.22      0.05      0.21      0.14      0.29   4249.52      1.00
transition_prob[0,1]      0.14      0.04      0.14      0.08      0.21   5060.77      1.00
transition_prob[0,2]      0.64      0.06      0.64      0.55      0.73   4550.78      1.00
transition_prob[1,0]      0.25      0.04      0.25      0.19      0.31   4561.80      1.00
transition_prob[1,1]      0.20      0.03      0.20      0.14      0.25   5155.01      1.00
transition_prob[1,2]      0.56      0.04      0.56      0.49      0.63   5182.31      1.00
transition_prob[2,0]      0.08      0.02      0.08      0.05      0.11   4588.30      1.00
transition_prob[2,1]      0.32      0.03      0.32      0.28      0.37   5686.96      1.00
transition_prob[2,2]      0.60      0.03      0.60      0.55      0.64   4707.23      1.00
```
vs Stan
```
Inference for Stan model: anon_model_33c24889b03234cb7bb2407f5f463e01.
1 chains, each with iter=10000; warmup=5000; thin=1; 
post-warmup draws per chain=5000, total post-warmup draws=5000.

             mean se_mean     sd   2.5%    25%    50%    75%  97.5%  n_eff   Rhat
theta[1,1]   0.21  7.1e-4   0.04   0.13   0.18   0.21   0.24   0.31   3996    1.0
theta[2,1]   0.25  6.1e-4   0.04   0.18   0.22   0.25   0.27   0.32   3831    1.0
theta[3,1]   0.08  2.9e-4   0.02   0.05   0.07   0.08   0.09   0.12   3618    1.0
theta[1,2]   0.14  6.3e-4   0.04   0.07   0.11   0.14   0.17   0.23   4093    1.0
theta[2,2]    0.2  5.5e-4   0.03   0.14   0.17    0.2   0.22   0.26   3409    1.0
theta[3,2]   0.32  4.0e-4   0.03   0.27   0.31   0.32   0.34   0.37   4281    1.0
theta[1,3]   0.64  9.2e-4   0.06   0.53    0.6   0.64   0.68   0.75   3752    1.0
theta[2,3]   0.56  6.8e-4   0.04   0.47   0.53   0.56   0.58   0.64   3702    1.0
theta[3,3]    0.6  4.6e-4   0.03   0.54   0.58    0.6   0.62   0.65   3989    1.0
phi[1,1]   3.9e-3  1.6e-4   0.011.2e-18 2.1e-8 2.6e-5 1.3e-3   0.04   5384    1.0
phi[2,1]   3.5e-3  1.4e-4 9.9e-32.4e-18 1.6e-8 1.6e-5 1.2e-3   0.03   4727    1.0
phi[3,1]     0.17  3.2e-4   0.02   0.14   0.16   0.17   0.19   0.21   3954    1.0
phi[1,2]   2.8e-3  1.2e-4 8.2e-36.1e-20 1.1e-8 1.4e-5 9.5e-4   0.03   4939    1.0
phi[2,2]   1.9e-3  8.3e-5 5.2e-31.6e-17 1.1e-8 1.1e-5 7.5e-4   0.02   3952    1.0
phi[3,2]     0.03  1.6e-4 9.6e-3   0.02   0.03   0.03   0.04   0.05   3676    1.0
phi[1,3]     0.17  7.3e-4   0.04   0.09   0.14   0.17    0.2   0.26   3506    1.0
phi[2,3]   1.6e-3  6.6e-5 4.5e-38.9e-19 7.7e-9 8.4e-6 5.8e-4   0.02   4554    1.0
phi[3,3]   7.5e-4  3.0e-5 2.1e-31.4e-19 4.3e-9 5.3e-6 2.8e-4 7.3e-3   4949    1.0
phi[1,4]      0.8  8.5e-4   0.05   0.68   0.76    0.8   0.83   0.88   3640    1.0
phi[2,4]   2.5e-3  1.1e-4 7.5e-37.5e-19 3.0e-8 2.2e-5 1.0e-3   0.02   4913    1.0
phi[3,4]     0.03  2.8e-4   0.02 4.1e-3   0.01   0.02   0.04   0.07   3349    1.0
phi[1,5]   3.8e-3  1.3e-4 8.2e-31.4e-17 1.0e-7 9.7e-5 3.5e-3   0.03   3769    1.0
phi[2,5]   3.2e-3  9.3e-5 5.4e-31.1e-18 7.1e-7 4.7e-4 4.3e-3   0.02   3420    1.0
phi[3,5]   1.4e-3  4.0e-5 2.4e-32.8e-18 1.9e-7 1.6e-4 1.8e-3 8.3e-3   3657    1.0
phi[1,6]   6.5e-3  3.2e-4   0.021.6e-17 4.7e-8 6.1e-5 2.6e-3   0.06   3557    1.0
phi[2,6]   3.5e-3  1.4e-410.0e-39.2e-18 2.5e-8 2.7e-5 1.6e-3   0.03   5153    1.0
phi[3,6]     0.76  4.4e-4   0.03   0.71   0.74   0.76   0.78   0.81   3262    1.0
phi[1,7]   5.5e-3  2.8e-4   0.021.8e-18 3.7e-8 3.3e-5 2.0e-3   0.06   3312    1.0
phi[2,7]     0.69  6.6e-4   0.04   0.61   0.66   0.69   0.71   0.76   3682    1.0
phi[3,7]   1.4e-3  6.3e-5 4.2e-36.1e-20 4.6e-9 7.9e-6 5.2e-4   0.01   4323    1.0
phi[1,8]   1.2e-3  5.2e-5 3.5e-31.7e-18 7.6e-9 7.9e-6 4.8e-4   0.01   4486    1.0
phi[2,8]   6.2e-4  2.7e-5 1.9e-31.0e-18 4.0e-9 3.7e-6 2.2e-4 6.0e-3   5339    1.0
phi[3,8]   2.8e-4  1.3e-5 8.7e-41.2e-19 1.1e-9 1.7e-6 1.0e-4 2.7e-3   4537    1.0
phi[1,9]   8.5e-3  3.8e-4   0.029.6e-18 9.2e-8 9.6e-5 5.0e-3   0.08   3108    1.0
phi[2,9]      0.3  6.2e-4   0.04   0.22   0.27    0.3   0.32   0.37   3885    1.0
phi[3,9]   2.1e-3  1.2e-4 6.0e-31.8e-18 8.2e-9 1.2e-5 7.7e-4   0.02   2569    1.0
phi[1,10]  1.0e-3  4.7e-5 3.3e-33.1e-17 1.0e-8 9.2e-6 4.2e-4   0.01   4778    1.0
phi[2,10]  6.6e-4  2.8e-5 2.0e-31.6e-14 1.2e-8 6.1e-6 2.6e-4 6.4e-3   5057    1.0
phi[3,10]  2.6e-4  1.2e-5 8.3e-42.3e-179.5e-10 1.2e-6 8.1e-5 2.8e-3   4586    1.0
```

**Comment by fehiepsi** [comment]
Test on the example at https://jeffpollock9.github.io/going-NUTS-with-pyro-and-pystan/
```


                mean       std    median      5.0%     95.0%     n_eff     r_hat
     alpha     45.37      0.00     45.37     45.36     45.37   7092.12      1.00
   beta[0]      1.29      0.00      1.29      1.29      1.30   5277.55      1.00
   beta[1]      2.35      0.00      2.35      2.34      2.36   6375.87      1.00
   beta[2]      2.30      0.00      2.30      2.30      2.31   5866.32      1.00
   beta[3]    -11.23      0.00    -11.23    -11.23    -11.22   6053.15      1.00
   beta[4]     -1.86      0.00     -1.86     -1.86     -1.85   6609.08      1.00
   beta[5]     22.09      0.00     22.09     22.09     22.10   6392.07      1.00
   beta[6]     -6.38      0.00     -6.38     -6.39     -6.38   5183.83      1.00
   beta[7]      4.62      0.00      4.62      4.61      4.62   6212.75      1.00
     sigma      0.17      0.00      0.17      0.16      0.17   3292.61      1.00
```
which is a bit better than Stan, and 2x better than previously.

+ Stan
```
          mean se_mean     sd   2.5%    25%    50%    75%  97.5%  n_eff   Rhat
alpha    45.37  4.8e-5 3.4e-3  45.36  45.37  45.37  45.37  45.37   5143    1.0
beta[1]   1.29  4.8e-5 3.5e-3   1.29   1.29   1.29   1.29    1.3   5262    1.0
beta[2]   2.35  4.4e-5 3.3e-3   2.34   2.35   2.35   2.35   2.36   5702    1.0
beta[3]    2.3  5.1e-5 3.5e-3    2.3    2.3    2.3   2.31   2.31   4752    1.0
beta[4] -11.23  4.7e-5 3.4e-3 -11.23 -11.23 -11.23 -11.23 -11.22   5264    1.0
beta[5]  -1.86  4.6e-5 3.4e-3  -1.87  -1.86  -1.86  -1.86  -1.85   5451    1.0
beta[6]  22.09  4.3e-5 3.2e-3  22.08  22.09  22.09  22.09   22.1   5542    1.0
beta[7]  -6.38  4.8e-5 3.2e-3  -6.39  -6.38  -6.38  -6.38  -6.38   4662    1.0
beta[8]   4.62  4.5e-5 3.3e-3   4.61   4.62   4.62   4.62   4.63   5366    1.0
sigma     0.17  3.7e-5 2.4e-3   0.16   0.17   0.17   0.17   0.17   4192    1.0
lp__    3205.9    0.06   2.21 3200.8 3204.6 3206.2 3207.5 3209.2   1283    1.0
```
+ Pyro 
```

  | mean | std | 25% | 50% | 75% | neff | rhat
-- | -- | -- | -- | -- | -- | -- | --
alpha | 45.37 | 0 | 45.37 | 45.37 | 45.37 | 3078.48 | 1
beta[0] | 1.29 | 0 | 1.29 | 1.29 | 1.29 | 3047.63 | 1
beta[1] | 2.35 | 0 | 2.35 | 2.35 | 2.35 | 2774.76 | 1
beta[2] | 2.3 | 0 | 2.3 | 2.3 | 2.31 | 3313.62 | 1
beta[3] | -11.23 | 0 | -11.23 | -11.23 | -11.23 | 2983.01 | 1
beta[4] | -1.86 | 0 | -1.86 | -1.86 | -1.86 | 3293.98 | 1
beta[5] | 22.09 | 0 | 22.09 | 22.09 | 22.09 | 3107.56 | 1
beta[6] | -6.38 | 0 | -6.38 | -6.38 | -6.38 | 3048.57 | 1
beta[7] | 4.62 | 0 | 4.62 | 4.62 | 4.62 | 3366.54 | 1
sigma | 0.17 | 0 | 0.17 | 0.17 | 0.17 | 2201.37 | 1
```

**Comment by fehiepsi** [comment]
Thanks for discussions for this tricky issue, @neerajprad! This is good to review now. :)

**Comment by neerajprad** [comment]
Looks great! cc. @null-a: I think we'll probably need to make a few changes to brmp to get it working with numpyro master, though we should probably just wait for the next release, which should be out in a week or so.

**Pull request merged**
