### PR TITLE
Tutorial on Automatic Partial centering of model using LocScaleReparam

### PR DESCRIPTION
**Pull request by Madhav-Kanda**
Hi, based on the issue #1635,  I have created a tutorial on Automatic Partial centering of model by using Variationally Inferred Parameterisation.  I have tried to create the tutorial following the template similar to the recently added tutorials. Let me know if there are any mistakes or error in the tutorial.

### CODE REVIEW

**Comment by fehiepsi** [comment]
Awesome work! Thanks for the contribution, @Madhav-Kanda! Could you add the tutorial into the Introductory tutorial section of [this index file](https://github.com/pyro-ppl/numpyro/blob/master/docs/source/index.rst). Optionally, it would also be great to have a thumbnail for the tutorial in [this folder](https://github.com/pyro-ppl/numpyro/tree/master/docs/source/_static/img/tutorials). Thanks!

**Comment by fehiepsi** [comment]
Could you move the file to the notebooks folders? https://github.com/pyro-ppl/numpyro/tree/master/notebooks/source

**Comment by martinjankowiak** [comment]
thanks @Madhav-Kanda !

some additional comments:
- can you consistently use the z spelling for parameterization instead of mixing both spellings? including file names?
- nit: "the Neal's" => "Neal's"
- typo: hieratchical
- this phrase is confusing and should probably be removed: "under which the posterior is most like an independent normal distribution"

**Comment by Madhav-Kanda** [comment]
Thanks for the suggestions @martinjankowiak, I have made changes based on the last three points but, I couldn't understand the first point:
> * can you consistently use the z spelling for parameterization instead of mixing both spellings? including file names?

Could you please provide an example to explain what do you mean by this?

**Comment by martinjankowiak** [comment]
well as it stands file names and text switch back and forth between "(re)parameteri**Z**ation" and "(re)parameteri**S**ation"

**Comment by Madhav-Kanda** [comment]
@martinjankowiak, @fehiepsi, I have made the suggested changes. Let me know if I missed out on something. Thanks!

**Review by fehiepsi — APPROVED** [review]

**Comment by fehiepsi** [comment]
Thanks, @Madhav-Kanda!

**Pull request merged**
